### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by n0nuser** [n0nuser/Monitor#11]
# Web

## Tasks

- [x] #50
  - [APS](https://apscheduler.readthedocs.io/en/3.x/)
  - [Celery](https://realpython.com/asynchronous-tasks-with-django-and-celery/)
  - [Django RQ](https://github.com/rq/django-rq)
  - [Django Scheduler](https://github.com/llazzaro/django-scheduler)
- [x] n0nuser/Monitor#3
- [x] n0nuser/Monitor#5
- [ ] #61 
- [ ] Create ping task if there's no data in X time. (default 5 min.)
- [x] #51 

## Models

- [x] n0nuser/Monitor#40
- [x] n0nuser/Monitor#32
- [x] n0nuser/Monitor#30

## Authentication

- [ ] n0nuser/Monitor#1 
- [x] n0nuser/Monitor#24
  - [x] n0nuser/Monitor#26 
- [x] n0nuser/Monitor#39
- [x] n0nuser/Monitor#27
- [x] n0nuser/Monitor#10
- [x] n0nuser/Monitor#9

## Functionality

- [x] n0nuser/Monitor#35
  - [ ] Ability to save commands (will depend on OS: don't show Linux commands on Windows, or let the user decide).
  - [ ] Ability to save scripts: send commands in sequence, save results in a queue (data structure) and: print it and/or save it.
- [x] n0nuser/Monitor#8
- [ ] n0nuser/Monitor#6
- [x] n0nuser/Monitor#38
- [ ] n0nuser/Monitor#7
- [x] n0nuser/Monitor#4
- [x] n0nuser/Monitor#23
- [x] #48 
- [x] #47
- [x] #46
- [x] #45 

## Web design

- [x] Use a web template for Dashboard.
  - ~~[Django Volt](https://github.com/app-generator/django-volt-dashboard)~~
  - ~~[Creative Tim - Soft UI](https://www.creative-tim.com/product/soft-ui-design-system)~~
  - ~~[Shards UI](https://designrevision.com/demo/shards/)~~
  - [Shards Dashboard](https://designrevision.com/downloads/shards-dashboard-lite/)
- [x] n0nuser/Monitor#22
  - [x] General view of metrics: [Chart.js](https://chartjs.org).
- [x] n0nuser/Monitor#25
  - [x] In each host, customize with metrics. :thinking:
    - In this case, agents would have their data to show. New table with fields to show as boolean??

## Architecture

- [x] n0nuser/Monitor#12
  - [x] Change SQLite for PostgreSQL.
  - ~~Use memcached for caching.~~
  - [ ] If Celery is used, configure Redis.
  - [x] Use Docker-Compose when the project is finished.

# REST API

- [x] n0nuser/Monitor#18
- [x] n0nuser/Monitor#31
  - [x] n0nuser/Monitor#28
  - [x] n0nuser/Monitor#21

# Documentation and code optimization

- [x] #65
- [x] #15 
- [x] #16
